%%%% calchours.texi
%%%% Created by Laurence D. Finston (LDF) Thu Oct 17 19:09:25 CEST 2013

%%%% This file is part of the calchours User and Reference Manual.
%%%% Copyright (C) 2013, 2014 Laurence D. Finston
%%%% See the section "GNU Free Documentation License" in the file 
%%%% fdl.texi for copying conditions.


\input epsf 
\def\epsfsize#1#2{#1}

\newbox\PPbox % symbol for ++
\setbox\PPbox=\hbox{\kern.5pt\raise1pt\hbox{\sevenrm+\kern-1pt+}\kern.5pt}
\def\PP{\copy\PPbox}
\let\mc=\tenrm
\def\CPLUSPLUS{{\mc C\PP\spacefactor1000}}

\input texinfo   @c -*-texinfo-*-

@c %**start of header
@setfilename calchours.info
@settitle calchours User and Reference Manual
@c %**end of header

@set EDITION 1.0
@set VERSION 1.0
@set UPDATED October 17, 2013
@set UPDATE-MONTH October 2013

@documentlanguage en

@c *********************

@copying
calchours User and Reference Manual, edition @value{EDITION}.@*
The author is Laurence D. Finston.

Copyright @copyright{} 2013 Gesellschaft f@"{u}r wissenschaftliche
Datenverarbeitung mbH, G@"{o}ttingen, Germany

@quotation
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.2 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with the Front-Cover Texts being 
``calchours User and Reference Manual'',
and no Back-Cover Text.  A copy of the license is included in 
the section entitled ``GNU Free Documentation License.''
@end quotation
@end copying

@c *********************

@dircategory non-GNU packages
@direntry
* GWDG Archive Interface: (GWDG).  GWDG Archive Interface
@end direntry

@c *********************


@c @setchapternewpage odd
@c @setchapternewpage off  @c For saving paper.  LDF 2003.08.20.

@c *********************

@titlepage
@title calchours --- Calculate Working Hours 
@subtitle 
@subtitle User and Reference Manual edition @value{EDITION}
@subtitle Last updated @value{UPDATED}
@author Laurence D. Finston 
@sp 1
@author Gesellschaft f@"ur wissenschaftliche 
@author Datenverarbeitung mbH G@"ottingen 
@author (GWDG)

@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@headings on

@c Comment-out to save paper.
@shortcontents

@contents

@node Top, , (dir), (dir)

@ifnottex
@insertcopying
@end ifnottex

@menu
* Introduction::    

* Invoking::    

@detailmenu
--- The Detailed Node Listing ---

Introduction

* Introduction::


Invoking

* Invoking::

@end detailmenu

@end menu

@macro cpp {}
@iftex
@tex
@CPLUSPLUS
@end tex
@end iftex
@ifnottex
C++
@end ifnottex
@end macro



@iftex
@tex
\global\pageno=1
@end tex
@end iftex

@c Introduction

@include intro.texi

@c Invoking

@include invoking.texi


@bye

@c * (1)

@c Emacs-Lisp code for use in indirect buffers:
@c
@c (progn (texinfo-mode) (outline-minor-mode t) (setq outline-regexp "@c *\\*+"))

@c * (1) Local Variables for Emacs

@c Local Variables:
@c mode:Texinfo
@c abbrev-mode:t
@c eval:(outline-minor-mode t)
@c End:


